"""init v1 tables: videos and video_metrics_snapshot

Revision ID: fefc8e82a7b3
Revises: bfdf264aa3ce
Create Date: 2025-10-08 15:37:21.679277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fefc8e82a7b3'
down_revision = 'bfdf264aa3ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###